### ISSUE TITLE
Back button prematurely closes the app

### ISSUE THREAD

**Issue by securit** [FokkeZB/Tracker#26]
Hi, 
under Android 6.0.1 clicking the back button appears to close the app rather than backgrounding it. Would it be possible to add a dialog box to pop up and say "are you sure you want to exit" when tracking?
What about using intents as a way to keep the application running as a task?

I tried something like this.
in tracker.xml:

```xml
<Window id="win" onAndroidback="doAndroidBack" titleid="Tracking">
```

in tracker.js in the SEF

```js
(function() {
  if (OS_ANDROID) { 
  	$.win.onBack = doAndroidBack; 
 }
```

and later

```js
function doAndroidBack() {
	if (ride.isTracking()){
		var dialog = Ti.UI.createAlertDialog({
	    	title: 'Closing tracker',
	    	message: 'Closing tracker will stop recording. Are you sure?',
	    	buttonNames: ['Yes', 'No'],
	    	cancel: 1
	  	});
	  	dialog.show();
	  	dialog.addEventListener('click', function (e) {
    		if (e.index === 0) {
    			Ti.UI.currentWindow.close();
    		}
    	});
	} else {
		Ti.UI.currentWindow.close();
	}  	
}
```

but this did not have the desired effect.

**Comment by FokkeZB** [comment]
Hi @securit 

The right way to force an app to background is to use this for `androidback`:

```js
                var intent = Ti.Android.createIntent({
                    action: Ti.Android.ACTION_MAIN
                });
                intent.addCategory(Ti.Android.CATEGORY_HOME);
                Ti.Android.currentActivity.startActivity(intent);
```

**Comment by securit** [comment]
I get a 
    [ERROR] :  TiExceptionHandler: (main) [659,659] ----- Titanium Javascript Runtime Error -----
    [ERROR] :  TiExceptionHandler: (main) [0,659] - In /alloy/controllers/index.js:53,10
    [ERROR] :  TiExceptionHandler: (main) [0,659] - Message: Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    [ERROR] :  TiExceptionHandler: (main) [0,659] - Source:     $.win.addEventListener("androidback", function() {
    [ERROR] :  V8Exception: Exception occurred at /alloy/controllers/index.js:53: Uncaught TypeError: Cannot read property 'addEventListener' of undefined
with that.
I think that may be related to the change in behavior as per https://jira.appcelerator.org/browse/TIMOB-19919. 
and that $.win doesnt exist until the track tab is loaded, so shouldnt the 2nd line be `$.index.onBack `?

**Comment by FokkeZB** [comment]
Ah, sorry for that copy paste error. Fixed!

**Comment by securit** [comment]
Thats better :)
Any idea as to how I stop users from Swiping the app away?

**Comment by FokkeZB** [comment]
Not sure what you mean?

**Comment by securit** [comment]
Like this http://www.itworld.com/article/2693446/closing-android-apps-by-swiping-them-away-what-that-actually-does.html <http://www.itworld.com/article/2693446/closing-android-apps-by-swiping-them-away-what-that-actually-does.html>

I think it needs to run as a service instead ?

http://stackoverflow.com/questions/3529834/how-to-keep-an-android-app-running-indefinitely

http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Android.Service

**Comment by FokkeZB** [comment]
Mmm, that would be a good question to ask e.g. @hansemannn. Looks like Titanium could have an event or config to let you decide how to respond to a swipe-quit.

**Comment by securit** [comment]
I have been looking at using an IntentService, but haven't managed to 
get it to start the intent yet... with code like the examples on the 
Appcelerator website...

var durationInterval;
var lastData;

if (OS_ANDROID) {
	var SECONDS = 5;
	var URL = 'androidgps.js';

     Ti.API.info('***starting service***');

     var intent = Ti.Android.createServiceIntent({
     		url: URL
     	});

     // Service should run its code every SECS seconds
     intent.putExtra('interval', SECONDS * 1000);
     intent.putExtra('message', 'Hi from started service');

     var service = Ti.Android.createService(intent);

     service.start();
     service.stop();
}

**Comment by securit** [comment]
I found bencoding/Alarmmanager and thought that it would lend it self nicely to running the GPS logging code in the background, which it does wonderfully, but I can't get it to stop. I see you also forked his code. Did you ever get it to compile correctly? I was wondering if it was a problem with 6.0.2.GA which I am running on.

**Comment by FokkeZB** [comment]
Hi @securit, I've used the module a couple of times, but that was looooong ago. Id suggest asking the author.
