### ISSUE TITLE
Ability to pause

### ISSUE THREAD

**Issue by securit** [FokkeZB/Tracker#27]
How would you go about implementing a pause or more specifically, if I restart the tracking anytime less than 5 mins after the previous track ended, append to that track and not a new one.

**Comment by FokkeZB** [comment]
You'd either have to rework the logic around starting and stopping in https://github.com/FokkeZB/Tracker/blob/master/app/lib/track.js or add a feature where the user would be able to select another track to merge with afterwards and then remap the track IDs for those data records. I'd go for the latter, or at least ask the user to confirm if they want to continue with the previous track.
